### ISSUE TITLE
AM/PM Should be the default for US English Keyboard language

### ISSUE THREAD

**Issue by D0J0P** [elementary/switchboard-plug-datetime#107] opened 2023-01-31 22:18 UTC
### What Happened?

24-hr time is shown for me by default on a clean install, but I think it would be better to have AM/PM set by default if my default keyboard layout is US English. 

Everyone in North America, with the exception of some in Quebec, use AM/PM by default. I think having it set to AM/PM by  default for US English keyboards but not French Canadian keyboards would make sense. 

This also occurs when setting up the On-Boarding for installing elementary OS. US English is chosen by default, probably because it knows from the download that I'm in North America and speak English, so having a way to have AM/PM picked according to keyboard layout there would be great. 

### Steps to Reproduce

1. Install elementary OS Horus
2. Select US English keyboard layout
3. Look at the time and see that it's set to 24-hr time instead of AM/PM

### Expected Behavior

That AM/PM would be the default time layout for my keyboard layout.

Note: I'm on 7 Horus stable even though that's not an option below yet.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment] 2024-02-10 20:21
Duplicate of https://github.com/elementary/initial-setup/issues/70

**Closed by danirabbit** 2024-02-10 20:21 UTC
