### ISSUE TITLE
Selected time format is not global

### ISSUE THREAD

**Issue by Sebzlol** [elementary/switchboard-plug-datetime#49] opened 2018-10-21 17:00 UTC
If you select 24H time format it still shows AM/PM several places.

Examples are at the lock screen and in the calendar. Might be other places too.

**Comment by peteruithoven** [comment] 2018-10-21 17:18
Thanks for the report! This is actually a duplicate of / related to:
- https://github.com/elementary/greeter/issues/52
- https://github.com/elementary/greeter/issues/171
- https://github.com/elementary/calendar/issues/268

**Closed by peteruithoven** 2018-10-21 17:18 UTC
