### ISSUE TITLE
24-hour time format must be activated by default

### ISSUE THREAD

**Issue by gmikhail** [elementary/switchboard-plug-datetime#54] opened 2019-01-04 16:09 UTC
After installation, the 24-hour format should have been activated by default, at least in countries such as Ukraine and Russia (and a bunch of other non-English speaking countries).

![2019-01-03 173917](https://user-images.githubusercontent.com/4838367/50697427-df361a80-104a-11e9-8f92-865d092f6767.png)

**Comment by ryonakano** [comment] 2021-02-20 13:52
Closing as a duplicate of elementary/initial-setup#70

**Closed by ryonakano** 2021-02-20 13:52 UTC
