### ISSUE TITLE
Plug looks too cluttered with switches

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/switchboard-plug-datetime#93] opened 2021-04-07 08:14 UTC
## Problem

Plug looks too cluttered with switches at the bottom of the view.

![Screenshot from 2021-04-07 16-10-14](https://user-images.githubusercontent.com/31680656/113833012-bff33e00-97bb-11eb-999b-b3f4fcae8c9d.png)

Contrast this to other plugs like the Desktop plug for instance where there is as good mix of switches and other widgets.
![Screenshot from 2021-04-07 16-09-02](https://user-images.githubusercontent.com/31680656/113832872-99350780-97bb-11eb-969e-cd7847341247.png)

## Proposal

Remove the ability to choose whether or not to show the date and the day of the week. I'm not sure how many people actually choose not to show the date and day though, so a poll may be appropriate to see what percentage of users actually disable these options.

## Prior Art

None

**Comment by cassidyjames** [comment] 2021-04-07 16:50
I'm gonna consider this a duplicate of #92 since it also covers the awkward layout here. But these features were just added, so I don't think it makes sense to immediately remove them; we should lay this out better. :)

**Closed by cassidyjames** 2021-04-07 16:50 UTC
Labels: Needs Design, Priority: Wishlist
