### ISSUE TITLE
Add option to sync current timezone from geolocation

### ISSUE THREAD

**Issue by jmc-88** [elementary/switchboard-plug-datetime#57] opened 2019-05-22 21:30 UTC
Currently, elementary provides the option to sync the clock for the current timezone with network time. It would be nice to also have the option to sync the _current timezone itself_ through geolocation data -- Chrome OS currently does this and I find it to be a very convenient feature.

For geolocation, IP address is a good clue provided a VPN is not in use. This is exactly what [tzupdate](https://github.com/cdown/tzupdate) uses.

**Comment by danrabbit** [comment] 2019-06-04 01:37
Closing as a duplicate of #3

**Closed by danrabbit** 2019-06-04 01:37 UTC
