### ISSUE TITLE
The current time zone is not shown unless selected manually

### ISSUE THREAD

**Issue by tapdancer** [elementary/switchboard-plug-datetime#108] opened 2023-02-10 11:47 UTC
### What Happened?

The selected time zone is not shown when relying on the 'Based on location'-option to select it for you. This left me in the dark as to why eOS was showing the incorrect time. Manually selecting the correct time zone got the time setting right.

### Steps to Reproduce

Open the 'Date and Time' settings panel in the System Settings app

### Expected Behavior

The 'Date and Time' panel should always show the currently selected time zone, whether selected manually or automatically.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by marco4mp** [comment] 2023-06-24 20:02
HI. It looks like a duplicate of https://github.com/elementary/switchboard-plug-datetime/issues/96

**Closed** 2023-06-24 21:35 UTC
