### ISSUE TITLE
pi 400 Location Based Time Zone Does Not Work

### ISSUE THREAD

**Issue by SwiftLemon** [elementary/switchboard-plug-datetime#90] opened 2021-02-13 01:53 UTC
## What Happened

With location services enabled and the option to set time zone "Based on your Location" is set to on. The time zone does not automatically update to location.

## Expected Behavior

Time zone should have been set automatically via location.

## Steps to Reproduce

1. Ensure location services are enabled
2. Date & Time system settings menu
3. Select "Based on your Location"

## Platform Information

Build: elementaryos-6.0-daily-rpi-20210212
Device: Raspberry Pi 400

**Comment by selwynorren** [comment] 2021-06-16 22:00
I have the exact same issue, however I am running the latest daily build for Standard Desktop

**Comment by ryonakano** [comment] 2022-08-14 12:51
Closing as duplicate of #96

**Closed by ryonakano** 2022-08-14 12:51 UTC
