### ISSUE TITLE
[Odin beta 1 and 2] Turning on "based on location" and "network time" doesn't give accurate time 

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/switchboard-plug-datetime#96] opened 2021-06-17 22:11 UTC
When I first installed both beta 1 and 2, both "Network time" and "Based on location" were turned on in settings/Date & Time, but that still gave the wrong time zone and time on the clock in the panel. I had to turn both off and set my time zone manually to get the correct time on the clock in the panel. Location is enabled in the "security & privacy" setting. I remember it causing issues for updating and upgrading through terminal and AppCenter until I did some search on the web and some random post mentioned fixing the time zone.

**Comment by ChaseClark** [comment] 2021-08-09 14:15
I am having the same issue on Odin Beta 2.

**Comment by marco4mp** [comment] 2021-08-12 23:16
The problem is still present in a fresh installation of elementary 6 Odin (Stable)

**Comment by marco4mp** [comment] 2023-06-24 20:43
Hello. I did a fresh install of elementary 7 (20230129rc.iso) and this problem persisted. 
But, after applying the pending updates (via terminal) the time automatically changed to the one that corresponds to my location. I also received the corresponding notification.


![Captura de pantalla Zona horaria actualizada](https://github.com/elementary/switchboard-plug-datetime/assets/52709674/c281ec21-e0da-4401-b686-8143f4c3c7be)




So I think the problem is solved!

**Comment by ryonakano** [comment] 2023-06-24 21:34
Yes, this should be fixed by https://github.com/elementary/default-settings/pull/279.

**Closed by ryonakano** 2023-06-24 21:34 UTC
Labels: Status: Confirmed, Priority: Medium
